# build dashboard
FROM node:20 AS dashboard-builder

WORKDIR /tmp
RUN git clone https://github.com/LaoYutang/clash-and-dashboard.git

WORKDIR /tmp/clash-and-dashboard
RUN npm install -g pnpm
RUN pnpm install && pnpm build

# build nginx
FROM alpine:latest AS nginx-builder

RUN apk add --no-cache build-base pcre-dev zlib-dev openssl-dev git wget

ARG NGINX_VERSION=1.24.0
ARG PATCH_FILE=proxy_connect_rewrite_102101.patch

WORKDIR /tmp
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && tar -zxvf nginx-${NGINX_VERSION}.tar.gz
RUN git clone https://github.com/chobits/ngx_http_proxy_connect_module.git

WORKDIR /tmp/nginx-${NGINX_VERSION}
RUN patch -p1 < /tmp/ngx_http_proxy_connect_module/patch/${PATCH_FILE}
RUN ./configure \
    --prefix=/etc/nginx \
    --sbin-path=/usr/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/run/nginx/nginx.pid \
    --add-module=/tmp/ngx_http_proxy_connect_module \
    --with-http_ssl_module
RUN make && make install && make clean && rm -rf /tmp/*

# clash-and-dashboard
FROM --platform=$TARGETPLATFORM dreamacro/clash:v1.16.0
RUN apk add --no-cache pcre zlib openssl
RUN mkdir -p /run/nginx
EXPOSE 8080

COPY --from=nginx-builder /etc/nginx /etc/nginx
COPY --from=nginx-builder /usr/sbin/nginx /usr/sbin/nginx

COPY --from=dashboard-builder /tmp/clash-and-dashboard/dist /dashboard
COPY --from=dashboard-builder /tmp/clash-and-dashboard/build/nginx.conf /etc/nginx/nginx.conf
COPY --from=dashboard-builder /tmp/clash-and-dashboard/build/start.sh /

ENTRYPOINT [ "sh", "/start.sh" ]
